### ISSUE TITLE
How to inject ExecutionContext?

### ISSUE THREAD

**Issue by marconilanna** [danielnixon/playwarts#25]
Hi,

I have a Play project with PlayWarts and I love it.

I have all classes with a declared dependency on `ExecutionContext`. However, when I try to wire my app using MacWire, I get a warning when either or both `PlayGlobalExecutionContext` and `ScalaGlobalExecutionContext` are enabled, respectively.

How can I, then, pass an `ExecutionContext` to fulfill the declared dependency without resorting to `@SuppressWarnings(Array("org.danielnixon.playwarts.PlayGlobalExecutionContext"))`?

Thank you

**Comment by danielnixon** [comment]
Hi,

Thanks for the kind words.

If you take a look in [Execution.scala](https://github.com/playframework/playframework/blob/2.5.9/framework/src/play/src/main/scala/play/api/libs/concurrent/Execution.scala#L15) you'll see that Play's `play.api.libs.concurrent.Execution.defaultContext` comes from `play.core.Execution.internalContext`. And if you look at _that_ you'll see that it comes from the [global app's actor system's dispatcher](https://github.com/playframework/playframework/blob/2.5.9/framework/src/play/src/main/scala/play/core/Execution.scala#L19).

If you take a look at the [ExecutionContextProvider](https://github.com/playframework/playframework/blob/2.5.9/framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L272-L278), you'll see that Play configures Guice to provide the same execution context (i.e. the actor system's dispatcher) when using runtime dependency injection.

I assume you're using Play's [BuiltInComponentsFromContext](https://playframework.com/documentation/2.5.x/api/scala/index.html#play.api.BuiltInComponentsFromContext) as per the [MacWire example](https://github.com/playframework/play-macwire-di/blob/master/app/GreetingApplicationLoader.scala). `BuiltInComponentsFromContext` gives you access to the actor system, so it should be as simple as passing `actorSystem.dispatcher` to whichever of your components depend on an `ExecutionContext`.

**Comment by marconilanna** [comment]
@danielnixon thanks for the prompt and very detailed reply. i don't mean to take more of your time, but and for unit tests where we don't have a running app and can't access `BuiltInComponentsFromContext`, what's your recommendation?

also, for non-play scala projects, what do you consider the best practice to avoid `scala.concurrent.ExecutionContext.global`?

**Comment by danielnixon** [comment]
To your first question: I guess it depends what testing framework you're using. With specs2 you can add an `implicit ev: ExecutionEnv` parameter to your specification. ExecutionEnv gives you an execution context. Other testing frameworks might have something similar. I'd say it's also fine to use the global execution context here.

To your second: The global execution context is a good default choice (see e.g. [the global ExecutionContext makes your life easier](http://blog.jessitron.com/2014/02/scala-global-executioncontext-makes.html)), so it's probably a good compromise to refer to it once (or as few times as possible) and inject it into your components (via simple constructor args, MacWire, Guice, whatever) in order to avoid spraying globals all over the place. If using PlayWarts you'd have to use `SuppressWarnings`, but that's probably fine too. It sort of functions as documentation: "I'm doing something unusual here and I've consciously opted-in to ignoring the warning". You still get a compiler warning/error if a developer accidentally imports `scala.concurrent.ExecutionContext.global` elsewhere.
